<%@include file="../flows-shared/header.jsp"%>
<%@page import="net.ashu.shopping.service.EmailService"%>
<div class="container">

	<div class="row">


		<div class="col-sm-offset-4 col-sm-4">
			<div class="text-center">
				<p>${registerModel.user.firstName}
					${registerModel.user.lastName}</p>
				<h1>Welcome!</h1>
				<h3>brandgenius.net</h3>
				<h6>You can use your email address as username to login!</h6>
				<div>
					<a href="${contextRoot}/login" class="btn btn-lg btn-success">Login
						Here</a>
				</div>
			</div>
		</div>
		<c:set var="fullname"
			value="${registerModel.user.firstName} ${registerModel.user.lastName}"></c:set>
		<c:set var="email" value="${registerModel.user.email}"></c:set>
		<%!EmailService em;%>
		<%
			String fullname = (String) pageContext.getAttribute("fullname");
			String subject = "welcome to BrandGenius. You have Registered successfully";
			String email = (String) pageContext.getAttribute("email");
			String body = "Hey "+fullname+",\n"+
					"Thank you for joining BrandGenius.\n"+
					"Great offers awaiting."+
					"\n\nRegards,"+
					"\nTeam BrandGenius."+
					"\n\n\n\n\n\nthis is an autogenerated code! please do not reply";

			System.out.println(body);
			System.out.println(subject);
			System.out.println(email);
			em = new EmailService(email,subject,body);
		%>


	</div>


</div>
</div>
<%@include file="../flows-shared/footer.jsp"%>